spring.application.name=park-sure
#server.servlet.context-path=/park-sure

spring.datasource.url = jdbc:postgresql://localhost:5432/park_sure
spring.datasource.username = postgres
spring.datasource.password = admin


spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=park-sure


spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=park-sure-verify-group
spring.kafka.consumer.auto-offset-reset=earliest

topicName=park-sure-verify

org.springframework.security: DEBUG

server.port=8082
